import { mkdir, readFile, writeFile } from "node:fs/promises";
import type { SecretEntry } from "./types.ts";
import { envLayerDir } from "./paths.ts";
import { loadState, saveState } from "./state.ts";

function escapeEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

export async function setSecret(
  root: string,
  key: string,
  value: string,
  profile?: string,
): Promise<SecretEntry> {
  const state = await loadState(root);
  if (!state) {
    throw new Error("Not connected. Run `envo create` first.");
  }

  const activeProfile = profile ?? state.profile;
  const dir = envLayerDir(root);
  await mkdir(dir, { recursive: true });
  const envFile = `${dir}/${activeProfile}.local`;
  const nextLine = `${key}=${escapeEnvValue(value)}`;
  const file = Bun.file(envFile);
  const existing = (await file.exists()) ? await readFile(envFile, "utf8") : "";
  const lines = existing
    .split("\n")
    .filter((line) => line.length > 0 && !line.startsWith(`${key}=`));

  const header =
    lines.length > 0
      ? lines
      : [
          "# Generated by envo secrets set — do not commit",
          `# profile: ${activeProfile}`,
        ];

  await writeFile(envFile, [...header, nextLine, ""].join("\n"));

  return {
    key,
    profile: activeProfile,
    envFile,
  };
}

/** Declare keys an environment requires; doctor fails when they are absent. */
export async function requireSecrets(
  root: string,
  keys: string[],
  environment?: string,
): Promise<{ environment: string; requiredKeys: string[] }> {
  const state = await loadState(root);
  if (!state) {
    throw new Error("Not connected. Run `envo environment create` first.");
  }
  const envName = environment ?? state.environments?.[0]?.name ?? state.profile;
  const environments = state.environments ?? [];
  const env = environments.find((e) => e.name === envName);
  if (!env) throw new Error(`Environment not found: ${envName}`);
  env.requiredKeys = [...new Set([...(env.requiredKeys ?? []), ...keys])];
  state.environments = environments;
  await saveState(root, state);
  return { environment: envName, requiredKeys: env.requiredKeys };
}
